In [1]:
# import packages for analysis and modeling
import pandas as pd  # data frame operations
#from pandas.tools.plotting import scatter_matrix  # scatter plot matrix
import statsmodels.api as sm  # statistical models (including regression)
import statsmodels.formula.api as smf  # R-like model specification
import numpy as np  # arrays and math functions
import matplotlib.pyplot as plt  # 2D plotting
#import zipcodes
#import pyzipcode

from pandas import Series
from scipy.stats import uniform  # for training-and-test split
from scipy.stats import boxcox
from sklearn.tree import DecisionTreeRegressor  # machine learning tree
from sklearn.ensemble import RandomForestRegressor # ensemble method
from sklearn.metrics import mean_squared_error
from matplotlib import pyplot
from pprint import pprint
from matplotlib import pyplot
from statsmodels.tsa.arima_model import ARIMA
from statsmodels.tsa.arima_model import ARIMAResults
from math import sqrt


# create a differenced series
def difference(dataset, interval=1):
	diff = list()
	for i in range(interval, len(dataset)):
		value = dataset[i] - dataset[i - interval]
		diff.append(value)
	return diff



# invert differenced value
def inverse_difference(history, yhat, interval=1):
	return yhat + history[-interval]

In [2]:
house = pd.read_csv('clean_house_data.csv', encoding = "ISO-8859-1")
house.head()

,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06
0,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,1,337200.0,338200.0,339000.0,339700.0,...,1047600,1049400,1048800,1049900,1054300,1059400,1067800,1080400,1082300,1072200
1,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,2,210400.0,212200.0,212200.0,210700.0,...,338100,336700,336100,336200,335500,334200,333500,333500,333400,332300
2,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,3,502900.0,504900.0,506300.0,507200.0,...,1319100,1317900,1319800,1324200,1330000,1336400,1342000,1347400,1345200,1334500
3,77449,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,95400.0,95600.0,95800.0,96100.0,...,178500,179400,180300,181100,182100,183300,183000,181800,181800,182800
4,79936,El Paso,TX,El Paso,El Paso County,5,77300.0,77300.0,77300.0,77300.0,...,125700,126400,126900,127600,128200,128600,128900,128700,128500,128800

In [3]:
# going to do for 1 first
# AR 97 - 2017
ar = house.loc[house.State == 'AR']
ar = ar.drop(ar.loc[:,ar.columns[6:15]], axis=1)
ar = ar.drop(ar.loc[:,ar.columns[258:]], axis=1)
ar.head()

,RegionName,City,State,Metro,CountyName,SizeRank,1997-01,1997-02,1997-03,1997-04,...,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12
245,72401,Jonesboro,AR,Jonesboro,Craighead County,254,53000.0,53100.0,53200.0,53400.0,...,109200,109500,109300,108900,108500,108500,108800,109200,109400,109600
283,71913,Hot Springs,AR,Hot Springs,Garland County,294,79300.0,79100.0,78900.0,78900.0,...,143900,143700,144300,145400,145700,145700,146500,147400,147800,146700
588,72034,Conway,AR,Little Rock-North Little Rock-Conway,Faulkner County,608,82400.0,83400.0,84400.0,85300.0,...,170300,171300,172100,173100,173300,172700,171600,170500,169500,169000
770,72701,Fayetteville,AR,Fayetteville-Springdale-Rogers,Washington County,796,83800.0,84400.0,85000.0,85500.0,...,190600,192000,192700,193100,194300,195400,196400,198100,200400,202500
1438,72076,Jacksonville,AR,Little Rock-North Little Rock-Conway,Pulaski County,1483,60400.0,60900.0,61400.0,61800.0,...,96600,97400,97600,98400,99700,100100,99700,99400,97700,94400

In [4]:
#AR 2018 - pres
ar_validate = house.loc[house.State == 'AR']
ar_validate = ar_validate.drop(ar_validate.loc[:,ar_validate.columns[6:267]], axis=1)
ar_validate.head()

,RegionName,City,State,Metro,CountyName,SizeRank,2018-01,2018-02,2018-03,2018-04,...,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06
245,72401,Jonesboro,AR,Jonesboro,Craighead County,254,109800,110200,110900,111000,...,109600,110800,113800,116500,117500,117900,117800,117800,118900,120100
283,71913,Hot Springs,AR,Hot Springs,Garland County,294,145300,144900,145100,144700,...,146800,146900,147700,149000,150500,151300,151700,152000,151500,150300
588,72034,Conway,AR,Little Rock-North Little Rock-Conway,Faulkner County,608,169000,169200,169400,169700,...,172300,173400,174000,174300,174900,175700,175800,175000,174700,175000
770,72701,Fayetteville,AR,Fayetteville-Springdale-Rogers,Washington County,796,205300,209200,212600,214300,...,220700,223100,225200,227300,228800,229600,229700,229900,231800,234200
1438,72076,Jacksonville,AR,Little Rock-North Little Rock-Conway,Pulaski County,1483,92300,92500,93500,94700,...,100000,100400,101000,102000,103100,103200,103100,103000,103200,103500

In [5]:
#print(ar.columns[6:])
test = pd.melt(ar, id_vars=['RegionName'], value_vars=ar.columns[6:])

In [6]:
t = test.loc[test.RegionName == 72401]
print(test.shape)
print(t.shape)
print(len(test.RegionName.unique()))

(23436, 3)
(252, 3)
93

In [7]:
t2 = t.drop(t.loc[:,['RegionName']], axis=1)

In [390]:
#t2.variable = pd.to_datetime(t2.variable)
#t2.to_csv('test_time.csv', index=False)
#t_series = Series.from_csv('test_time.csv')
#t_series.values[1:]

In [9]:
# prepare data
X = t2.value
X = X.astype('float32')
X = X.values

#t_series
#X = t_series.values[1:]
#X = X.astype('float32')

train_size = int(len(X) * 0.50)
train, test = X[0:train_size], X[train_size:]
# walk-forward validation
history = [x for x in train]
predictions = list()

#'''
for i in range(len(test)):
    # difference data
    months = 12
    diff = difference(history, months)
    # predict
    model = ARIMA(diff, order=(2,1,0))
    model_fit = model.fit(trend='nc', disp=0)
    yhat = model_fit.forecast()[0]
    #print(yhat)
    yhat = inverse_difference(history, yhat, months)
    predictions.append(yhat)
    # observation
    obs = test[i]
    history.append(obs)
    print('>Predicted=%.3f, Expected=%3.f' % (yhat, obs))
# report performance
mse = mean_squared_error(test, predictions)
rmse = sqrt(mse)
print('RMSE: %.3f' % rmse)
#'''

>Predicted=91678.102, Expected=91500
>Predicted=91436.280, Expected=91300
>Predicted=91089.811, Expected=91100
>Predicted=90773.118, Expected=90800
>Predicted=90507.128, Expected=90700
>Predicted=90570.478, Expected=90700
>Predicted=90948.183, Expected=90800
>Predicted=90817.552, Expected=90800
>Predicted=90817.525, Expected=90800
>Predicted=90817.499, Expected=90700
>Predicted=90583.767, Expected=90600
>Predicted=90426.066, Expected=90600
>Predicted=90593.495, Expected=90600
>Predicted=90442.365, Expected=90500
>Predicted=90433.663, Expected=90400
>Predicted=90191.152, Expected=90400
>Predicted=90658.435, Expected=90400
>Predicted=90408.503, Expected=90400
>Predicted=90458.674, Expected=90400
>Predicted=90267.476, Expected=90500
>Predicted=90672.924, Expected=90500
>Predicted=90359.831, Expected=90400
>Predicted=90300.000, Expected=90300
>Predicted=90300.000, Expected=90400
>Predicted=90531.122, Expected=90600
>Predicted=90722.335, Expected=90900
>Predicted=91245.681, Expected=91200
>Predicted=91564.344, Expected=91600
>Predicted=91964.517, Expected=92000
>Predicted=92364.687, Expected=92400
>Predicted=92764.856, Expected=92600
>Predicted=92801.127, Expected=92600
>Predicted=92384.822, Expected=93100
>Predicted=93674.711, Expected=94100
>Predicted=95252.232, Expected=95100
>Predicted=96199.001, Expected=95300
>Predicted=95170.674, Expected=95100
>Predicted=94833.426, Expected=94900
>Predicted=94717.687, Expected=94700
>Predicted=94660.002, Expected=94200
>Predicted=93634.229, Expected=93500
>Predicted=92837.365, Expected=93200
>Predicted=92953.483, Expected=93000
>Predicted=92776.420, Expected=92600
>Predicted=92747.749, Expected=92000
>Predicted=91734.767, Expected=91200
>Predicted=90267.158, Expected=90200
>Predicted=88511.186, Expected=89200
>Predicted=88326.196, Expected=88300
>Predicted=87720.354, Expected=87700
>Predicted=87289.097, Expected=87500
>Predicted=87187.261, Expected=87600
>Predicted=87712.942, Expected=87800
>Predicted=88429.429, Expected=87900
>Predicted=87804.688, Expected=87400
>Predicted=86391.614, Expected=86800
>Predicted=86076.201, Expected=86000
>Predicted=85028.648, Expected=85700
>Predicted=85459.468, Expected=86100
>Predicted=86760.909, Expected=86700
>Predicted=87269.544, Expected=87300
>Predicted=87932.185, Expected=88200
>Predicted=89294.129, Expected=88900
>Predicted=89461.709, Expected=89300
>Predicted=89443.241, Expected=89500
>Predicted=89445.065, Expected=89500
>Predicted=88863.457, Expected=89900
>Predicted=90571.091, Expected=90700
>Predicted=91347.928, Expected=91600
>Predicted=92909.280, Expected=92100
>Predicted=92704.038, Expected=92200
>Predicted=91945.743, Expected=92300
>Predicted=92381.036, Expected=92600
>Predicted=93357.081, Expected=92500
>Predicted=92011.276, Expected=92100
>Predicted=91535.977, Expected=92300
>Predicted=92794.551, Expected=93000
>Predicted=93772.797, Expected=93900
>Predicted=95245.403, Expected=94600
>Predicted=95334.407, Expected=95200
>Predicted=95678.394, Expected=95400
>Predicted=95070.143, Expected=95200
>Predicted=94734.205, Expected=95200
>Predicted=95535.436, Expected=95700
>Predicted=96587.037, Expected=96300
>Predicted=96388.147, Expected=96900
>Predicted=97271.623, Expected=98000
>Predicted=99840.727, Expected=98800
>Predicted=99526.326, Expected=98800
>Predicted=98454.295, Expected=99100
>Predicted=99379.842, Expected=100200
>Predicted=101617.327, Expected=101100
>Predicted=101484.613, Expected=101600
>Predicted=101633.266, Expected=101900
>Predicted=102386.037, Expected=101900
>Predicted=102159.581, Expected=101700
>Predicted=101414.164, Expected=101200
>Predicted=100748.385, Expected=100700
>Predicted=100946.376, Expected=100200
>Predicted=99495.611, Expected=99300
>Predicted=97907.636, Expected=98400
>Predicted=98395.547, Expected=97900
>Predicted=98417.465, Expected=97600
>Predicted=97103.413, Expected=97600
>Predicted=97620.163, Expected=98500
>Predicted=99741.084, Expected=100100
>Predicted=101561.389, Expected=102000
>Predicted=103591.755, Expected=104200
>Predicted=105859.641, Expected=106600
>Predicted=108704.608, Expected=108500
>Predicted=109666.173, Expected=109400
>Predicted=109084.702, Expected=109900
>Predicted=110134.448, Expected=109900
>Predicted=109877.715, Expected=109300
>Predicted=108409.760, Expected=108800
>Predicted=108589.665, Expected=108900
>Predicted=110029.243, Expected=109200
>Predicted=109976.177, Expected=109500
>Predicted=110006.140, Expected=109300
>Predicted=109392.003, Expected=108900
>Predicted=108918.745, Expected=108500
>Predicted=107988.882, Expected=108500
>Predicted=108324.181, Expected=108800
>Predicted=109517.505, Expected=109200
>Predicted=109382.404, Expected=109400
>Predicted=109119.666, Expected=109600
RMSE: 423.579

In [10]:
# going to do for 1 first
# AR 97 - 2017
ar = house.loc[house.State == 'AR']
ar = ar.drop(ar.loc[:,ar.columns[6:15]], axis=1)
ar = ar.drop(ar.loc[:,ar.columns[258:]], axis=1)

ar_validate = house.loc[house.State == 'AR']
ar_validate = ar_validate.drop(ar_validate.loc[:,ar_validate.columns[6:267]], axis=1)

In [11]:
zips = ar.RegionName.unique()

train = pd.melt(ar, id_vars=['RegionName'], value_vars=ar.columns[6:])
train_region = train.loc[train.RegionName == zips[0]]
train_region.head()

test = pd.melt(ar_validate, id_vars=['RegionName'], value_vars=ar_validate.columns[6:])
test_region = test.loc[test.RegionName == zips[0]]
test_region.head()

X = train_region.value.astype('float32').values
Y = test_region.value.astype('float32').values
D = test_region.variable.values

In [12]:
train, test, date = X, Y, D
# walk-forward validation
history = [x for x in train]
predictions = list()

#'''
for i in range(len(test)):
    # difference data
    months = 12
    diff = difference(history, months)
    # predict
    model = ARIMA(diff, order=(2,1,0))
    model_fit = model.fit(trend='nc', disp=0)
    yhat = model_fit.forecast()[0]
    #print(yhat)
    yhat = inverse_difference(history, yhat, months)
    predictions.append(yhat)
    # observation
    obs = test[i]
    history.append(obs)
    print('Prediction for {} : ${}'.format(date[i], round(float(yhat),2)))
    #print('>Predicted=%.3f, Expected=%3.f' % (yhat, date[i]))
# report performance
mse = mean_squared_error(test, predictions)
rmse = sqrt(mse)
print('RMSE: %.3f' % rmse)
#'''

Prediction for 2018-01 : $110065.0
Prediction for 2018-02 : $110412.54
Prediction for 2018-03 : $110530.74
Prediction for 2018-04 : $111575.39
Prediction for 2018-05 : $110325.26
Prediction for 2018-06 : $109806.13
Prediction for 2018-07 : $108459.81
Prediction for 2018-08 : $109872.77
Prediction for 2018-09 : $109730.0
Prediction for 2018-10 : $109818.47
Prediction for 2018-11 : $112093.84
Prediction for 2018-12 : $117336.51
Prediction for 2019-01 : $118547.08
Prediction for 2019-02 : $117638.88
Prediction for 2019-03 : $118191.89
Prediction for 2019-04 : $116860.18
Prediction for 2019-05 : $117573.92
Prediction for 2019-06 : $120031.95
RMSE: 752.478